# Compiler and flags
CC      := gcc
CFLAGS  := -std=c17 -Wall -Wextra -I. -O2 -DNDEBUG -MMD -MP

# Sources and target
SRCS    := main.c database.c records.c sort.c summary.c banner.c
OBJECTS := $(patsubst %.c,build/%.o,$(SRCS))
TARGET  := cms_P5-4

# Default target
.PHONY: all
all: $(TARGET)

# Link
$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^

# Compile into build/ directory
build/%.o: %.c | build
	$(CC) $(CFLAGS) -c $< -o $@

# Ensure build dir exists
build:
	mkdir -p build

# Include dependency files generated by -MMD
-include $(OBJECTS:.o=.d)

# Clean
.PHONY: clean
clean:
	rm -rf build $(TARGET)
