# Compiler to use
CC = gcc

# Compilation flags:
# -std=c11       : use the C11 standard
# -Wall -Wextra  : enable warnings
# -I.            : add current directory to include path
# -O2            : optimization level 2
# -DNDEBUG       : disable assert/debug code
# -MMD -MP       : generate dependency (.d) files alongside object files
CFLAGS = -std=c11 -Wall -Wextra -I. -O2 -DNDEBUG -MMD -MP

# Linker flags: link the math library (required for roundf/round)
LDFLAGS = -lm

# Source files in the project
SRCS = main.c database.c records.c sort.c summary.c banner.c history.c

# Object files live in build/ (patsubst converts .c -> build/.o)
OBJS = $(patsubst %.c,build/%.o,$(SRCS))

# Dependency files generated by -MMD (one .d per .o)
DEPS = $(OBJS:.o=.d)

# Final executable name
TARGET = cms_P5-4

.PHONY: all clean

# Default target builds the program
all: $(TARGET)

# Ensure build directory exists
build:
	mkdir -p build

# Rule to compile each .c into build/%.o and generate dependency files
build/%.o: %.c | build
	$(CC) $(CFLAGS) -c $< -o $@

# Link the object files into the final executable.
$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET) $(LDFLAGS)

# Clean build artifacts and generated dependency files
clean:
	rm -rf build $(TARGET) $(DEPS)

# Include dependency files if they exist so make knows source header deps.
-include $(DEPS)